version: "3"
services:
    php:

        build:
            context: ./php
            args:
                VSC_USERNAME: ${VSC_USERNAME}
                VSC_USER_EMAIL: ${VSC_USER_EMAIL}

        user: ${VSC_USERNAME}
        volumes:
            - ../src:/var/www/html

        container_name: ${CONTAINER_NAME}
        networks:
            - database_app

    nginx:
        image: "nginx"
        environment:
            - NGINX_PORT=80
        ports:
            - "80:80"
        volumes:
            - ../nginx/conf.d:/etc/nginx/conf.d
            - ../nginx/log:/var/log/nginx
            - ../src:/var/www/html
        networks:
            - database_app

    node:
        image: "node"
        stdin_open: true
        volumes:
            - ../src:/var/www/html

networks:
    database_app:
        external: true